### ISSUE TITLE
Why ist "Millimeter" Missing in all Units?

### ISSUE THREAD

**Issue by TomaT3** [haimkastner/unitsnet-js#12]
Why ist Millimeter missing in all Units.
For example in length, acceleration, speed.
We have meters, centimeters, micrometers,...
But no millimeters.
Is there a reason for that?

**Comment by haimkastner** [comment]
The new fix published to the npm ([unitsnet-js@1.0.14](https://www.npmjs.com/package/unitsnet-js/v/1.0.14))
