### ISSUE TITLE
Will ESM module support be added?

### ISSUE THREAD

**Issue by X-MARIO** [haimkastner/unitsnet-js#51]

**Comment by haimkastner** [comment]
Hi @X-MARI

I'm not sure I fully understand the issue.

The library is written in and supports ESM import/export, as you can see also in the example snippet in the readme.

https://github.com/haimkastner/unitsnet-js/blob/64f63a91bd9aab9cabec64b85f85a9c8757975a5/README.md?plain=1#L39
